//
// Created by Kurama on 12/20/2022.
//
#pragma once

// Menu
#define SERVER_FRAMEWORK_MENU_ID 101
#define SERVER_FRAMEWORK_MENUITEM_EXIT 40001
#define SERVER_FRAMEWORK_MENUITEM_MODULE_INFO 40003
#define SERVER_FRAMEWORK_MENUITEM_BODY_INFO 40004
#define SERVER_FRAMEWORK_MENUITEM_MGV 40005 // Mointer Graph View
#define SERVER_FRAMEWORK_MENUITEM_LOG_VIEW 40007

// Icons