add_subdirectory(libs/JMX_Library/BSLib)
add_subdirectory(libs/JMX_Library/GFX/GFX3DFunction)
add_subdirectory(libs/JMX_Library/GFX/FM)
add_subdirectory(libs/JMX_Library/GFX/GFXMainFrame)
add_subdirectory(libs/JMX_Library/SROInterfaceLib)

add_subdirectory(libs/ClientNet)
add_subdirectory(libs/ClientLib)

add_subdirectory(libs/NavMesh)
add_subdirectory(libs/SimpleViewer)
add_subdirectory(libs/MathHelpers)
add_subdirectory(libs/TypeId)

add_subdirectory(tests)

add_subdirectory(support)
add_subdirectory(third-party/imgui)
add_subdirectory(third-party/ghidra)

add_subdirectory(DevKit_DLL)
add_subdirectory(libs/DiscordRichPresence)