//
// Created by Kurama on 12/23/2022.
//
#pragma once

#include "Windows.h"

// usaully using by handshaes packets
#define HANDSHAKE_MSG_FLAG_IDFIELD_DUMMYMASK 0x1000u
#define HANDSHAKE_MSG_FLAG_IDFIELD_REQMSG 0x5000u
#define HANDSHAKE_MSG_FLAG_IDFIELD_ACKMSG 0x9000u

// using by server modules "Framework"
#define FRAMEWORK_MSG_FLAG_IDFIELD_DUMMYMASK 0x2000u
#define FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG 0x6000u
#define FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG 0xA000u

// using by client
#define CLIENT_MSG_FLAG_IDFIELD_DUMMYMASK 0x3000u
#define CLIENT_MSG_FLAG_IDFIELD_REQMSG 0x7000u
#define CLIENT_MSG_FLAG_IDFIELD_ACKMSG 0xB000u

// as always stolen from SRO_Clinet florain0
// https://gitlab.com/florian0/sro_devkit/-/blob/devel/source/libs/ClientLib/src/SRO_MSG_DEF.h
#define SAFE_DEFINE_MSGID(name, id, type) \
    static const WORD name = id ##u | type;

SAFE_DEFINE_MSGID(FRAMEWORKMSG_SETUPCORD, 0x0001, FRAMEWORK_MSG_FLAG_IDFIELD_DUMMYMASK) //0x2001

SAFE_DEFINE_MSGID(FRAMEWORKMSG_CERTIFICATE_REQ, 0x0003, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6003
SAFE_DEFINE_MSGID(FRAMEWORKMSG_CERTIFICATE_ACK, 0x0003, FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA003

SAFE_DEFINE_MSGID(FRAMEWORKMSG_NOTIFY, 0x0005, FRAMEWORK_MSG_FLAG_IDFIELD_DUMMYMASK) //0x2005
SAFE_DEFINE_MSGID(FRAMEWORKMSG_NOTIFY_REQ, 0x0005, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6005

SAFE_DEFINE_MSGID(FRAMEWORKMSG_LOG, 0x000A, FRAMEWORK_MSG_FLAG_IDFIELD_DUMMYMASK) //0x200A

SAFE_DEFINE_MSGID(SR_NOTIFY, 0x000C, CLIENT_MSG_FLAG_IDFIELD_DUMMYMASK) //0x300C

/// --------------------------------------------------------------------------
/// SR_NOTIFY
/// --------------------------------------------------------------------------
#define SR_NOTIFY_UNIQUE_SPAWN 0x00000C05
#define SR_NOTIFY_UNIQUE_KILLED 0x00000C06
#define SR_NOTIFY_ROC_QUEST 0x00000C16
/// --------------------------------------------------------------------------

SAFE_DEFINE_MSGID(SR_CHAT_REQ, 0x0025, CLIENT_MSG_FLAG_IDFIELD_REQMSG) //0x7025
SAFE_DEFINE_MSGID(SR_CHAT_ACK, 0x0025, CLIENT_MSG_FLAG_IDFIELD_ACKMSG) //0xB025

SAFE_DEFINE_MSGID(FRAMEWORKMSG_SHUTDOWN_SERVER_REQ_BY_CERT, 0x0108, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6108
SAFE_DEFINE_MSGID(FRAMEWORKMSG_SHUTDOWN_SERVER_ACK_BY_CERT, 0x0108, FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA108

SAFE_DEFINE_MSGID(FRAMEWORKMSG_THIRD_PARTY_MSG_REQ, 0x0110, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6110

SAFE_DEFINE_MSGID(FRAMEWORKMSG_REGISTER_SHARD_USER_ACK, 0x0204, FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA204

SAFE_DEFINE_MSGID(FRAMEWORKMSG_SHARD_USER_CHANGE_CONTENT_SERVER_NOTIFY_REQ, 0x0208,
                  FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6208
SAFE_DEFINE_MSGID(FRAMEWORKMSG_SHARD_USER_CHANGE_CONTENT_SERVER_NOTIFY_ACK, 0x0208,
                  FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA208

SAFE_DEFINE_MSGID(FRAMEWORKMSG_RELAY_MSG_TO_CLIENT_SINGLE, 0x0209, FRAMEWORK_MSG_FLAG_IDFIELD_DUMMYMASK) //0x2209

SAFE_DEFINE_MSGID(FRAMEWORKMSG_FACULTY_TEST_REQ, 0x0300, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6300
SAFE_DEFINE_MSGID(FRAMEWORKMSG_FACULTY_TEST_ACK, 0x0300, FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA300

SAFE_DEFINE_MSGID(FRAMEWORKMSG_OPERATE_SERVICE_REQ, 0x0303, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6303
SAFE_DEFINE_MSGID(FRAMEWORKMSG_OPERATE_SERVICE_ACK, 0x0303, FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA303

SAFE_DEFINE_MSGID(FRAMEWORKMSG_REFRESH_SHARD_DATA, 0x0311, FRAMEWORK_MSG_FLAG_IDFIELD_DUMMYMASK) //0x2311

SAFE_DEFINE_MSGID(FRAMEWORKMSG_TRANSFERFILE_REQ, 0x0404, FRAMEWORK_MSG_FLAG_IDFIELD_REQMSG) //0x6404
SAFE_DEFINE_MSGID(FRAMEWORKMSG_TRANSFERFILE_ACK, 0x0404, FRAMEWORK_MSG_FLAG_IDFIELD_ACKMSG) //0xA404

SAFE_DEFINE_MSGID(SR_SHARDJOB_REQ, 0x0808, CLIENT_MSG_FLAG_IDFIELD_REQMSG) //0x7808
SAFE_DEFINE_MSGID(SR_SHARDJOB_ACK, 0x0808, CLIENT_MSG_FLAG_IDFIELD_ACKMSG) //0xB808

SAFE_DEFINE_MSGID(SR_PARTY_UPDATE, 0x0864, CLIENT_MSG_FLAG_IDFIELD_DUMMYMASK) //0x3864
